apiVersion: apps/v1
kind: Deployment
metadata:
  name: 0-x-game
  labels:
    app: 0-x-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 0-x-game
  template:
    metadata:
      labels:
        app: 0-x-game
    spec:
      containers:
      - name: 0-x-game
        image: ghcr.io/chandankr111/0-x-game:sha-666053ace242bd38e156f4a1963c2f239aa177bc
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: github-container-registry
